In [2]:
import pickle
import numpy as np

In [7]:
with open('data.exp21', 'rb') as f:
    # The protocol version used is detected automatically, so we do not
    # have to specify it.
    data21 = pickle.load(f)
    
with open('data.exp15', 'rb') as f:
    # The protocol version used is detected automatically, so we do not
    # have to specify it.
    data15 = pickle.load(f)

In [8]:
data21['biasN']

array([ 0.01623978, -0.00641624, -0.01704422, -0.04228936, -0.03031682,
        0.01001601,  0.01274553, -0.03019769,  0.02519089, -0.00242452,
        0.00931919, -0.02993611,  0.00130954,  0.00356306,  0.03719285,
       -0.0130466 ,  0.00432809,  0.03832594, -0.034164  , -0.00104417,
       -0.01245603,  0.02634985, -0.01840238, -0.03085514,  0.02896857,
       -0.0056759 , -0.02037109, -0.04046641, -0.04139223,  0.02531577,
       -0.0126313 ,  0.01384922,  0.00501218,  0.01269511, -0.01527804,
        0.01514922, -0.02177044,  0.01683563,  0.00630355, -0.007344  ,
       -0.04101431,  0.02917429, -0.02381646, -0.02553455, -0.0062912 ,
        0.04376914, -0.00462476, -0.03752583,  0.03664156, -0.01013831,
        0.03677381, -0.03947284, -0.0395264 ,  0.02234167,  0.02672001,
       -0.01634786,  0.00467689,  0.03803409,  0.02128402, -0.0292225 ,
        0.01636333, -0.01841909, -0.01163011, -0.01188608, -0.00314357,
       -0.03149364, -0.00831763,  0.04280058,  0.03246025, -0.02

In [10]:
data21['weightN']

array([[ 0.03378815,  0.03668151, -0.01035348, ..., -0.00814605,
         0.00363487, -0.04056899],
       [ 0.0137552 , -0.0337145 , -0.02796363, ..., -0.01686468,
        -0.03798779, -0.02796658],
       [ 0.0246154 , -0.00659903,  0.01876977, ..., -0.00360101,
        -0.00424236, -0.02769785],
       ...,
       [ 0.03693757,  0.01493628,  0.04011387, ..., -0.03965859,
         0.03785617,  0.02567006],
       [-0.03396061,  0.0364322 ,  0.01683399, ..., -0.0094597 ,
        -0.02082995,  0.03635282],
       [ 0.00192947, -0.00533535, -0.00010517, ..., -0.03800409,
         0.01645506,  0.02790174]], dtype=float32)

In [11]:
data15['weightN']

array([[ 0.03378815,  0.03668151, -0.01035348, ..., -0.00814605,
         0.00363487, -0.04056899],
       [ 0.0137552 , -0.0337145 , -0.02796363, ..., -0.01686468,
        -0.03798779, -0.02796658],
       [ 0.0246154 , -0.00659903,  0.01876977, ..., -0.00360101,
        -0.00424236, -0.02769785],
       ...,
       [ 0.03693757,  0.01493628,  0.04011387, ..., -0.03965859,
         0.03785617,  0.02567006],
       [-0.03396061,  0.0364322 ,  0.01683399, ..., -0.0094597 ,
        -0.02082995,  0.03635282],
       [ 0.00192947, -0.00533535, -0.00010517, ..., -0.03800409,
         0.01645506,  0.02790174]], dtype=float32)

In [14]:
input21 = data21['inputN']
np.where(input21>0.1)

(array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([ 36,  70,  92, 100, 102, 232, 240, 294, 444, 454]))

In [15]:
input15 = data15['inputN']
np.where(input15>0.1)

(array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([ 36,  70,  92, 100, 102, 130, 232, 240, 294, 454]))